import { Helmet } from "react-helmet-async";

export default function Terms() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8 space-y-6">
      <Helmet>
        <title>Terms & Conditions – ToolStack</title>
        <meta
          name="description"
          content="Terms and conditions governing the use of ToolStack tools and services."
        />
      </Helmet>

      <h1 className="text-3xl font-bold">Terms & Conditions</h1>

      <p>
        Welcome to ToolStack. By accessing or using this website, you agree
        to comply with and be bound by the following Terms and Conditions.
        If you do not agree with any part of these terms, please do not use
        this website.
      </p>

      <h2 className="text-xl font-semibold">Use of the Website</h2>
      <p>
        ToolStack provides free online tools and utilities for informational
        and productivity purposes. You agree to use the website only for
        lawful purposes and in a way that does not harm the website or
        other users.
      </p>

      <h2 className="text-xl font-semibold">Accuracy of Tools</h2>
      <p>
        While we strive to ensure that the tools provide accurate results,
        ToolStack does not guarantee the completeness, reliability, or
        accuracy of any calculations or outputs generated by the tools.
        Users should independently verify important results.
      </p>

      <h2 className="text-xl font-semibold">Intellectual Property</h2>
      <p>
        All content, tools, design elements, and code on ToolStack are the
        property of the website unless otherwise stated. Unauthorized
        reproduction, redistribution, or copying of content is prohibited
        without permission.
      </p>

      <h2 className="text-xl font-semibold">Third-Party Services</h2>
      <p>
        ToolStack may use third-party services such as Google AdSense and
        analytics providers. These services may collect information in
        accordance with their own privacy policies.
      </p>

      <h2 className="text-xl font-semibold">Limitation of Liability</h2>
      <p>
        ToolStack will not be held responsible for any loss, damage, or
        consequences resulting from the use of this website or reliance on
        the information provided by the tools.
      </p>

      <h2 className="text-xl font-semibold">Changes to Terms</h2>
      <p>
        We may update these Terms and Conditions at any time without prior
        notice. Continued use of the website after changes are posted
        constitutes acceptance of the updated terms.
      </p>

      <h2 className="text-xl font-semibold">Contact</h2>
      <p>
        If you have any questions about these Terms and Conditions, please
        contact us through the contact page on this website.
      </p>
    </div>
  );
}